### ISSUE TITLE
Pixel 2 lock screen bug

### ISSUE THREAD

**Issue by WyldOne91** [Magisk-Modules-Repo/bariol-font#4]
The bug was fixed with a previous version but seems to have been reintroduced with the latest update.

**Comment by juzman** [comment]
Also happening on Pixel 2 XL.

**Comment by P1N2O** [comment]
Thanks for reporting. I was trying to fix some Greek characters and this bug appeared again.
Sorry guys, really busy. Will try to fix it soon (in a week or so)..

**Comment by P1N2O** [comment]
Hopefully this is fixed..
