### ISSUE TITLE
Android 9.0 Compatibility

### ISSUE THREAD

**Issue by Flobengogen** [Magisk-Modules-Repo/bariol-font#6]
I moved onto Android Pie and noticed that the ":" on the lockscreen clock is broken. Not sure if this is a the Pie's font issue or something. Please let me know if addition info or logs are required. cheers
![screenshot_20180901-195412](https://user-images.githubusercontent.com/37652764/44944826-f953b800-ae20-11e8-9b4c-0633b97ac7d3.png)

**Comment by P1N2O** [comment]
Which Pie build are you on? Pure AOSP or others like (RR, crDroid etc.)..??

**Comment by Flobengogen** [comment]
Im on the "PixelExperience" build of AOSP for Oneplus 5 
Link  to XDA - https://forum.xda-developers.com/oneplus-5/development/rom-pixel-experience-t3832702

**Comment by P1N2O** [comment]
There's problem with some custom ROM's like RR & PE..
I'll try to fix this somehow..

**Comment by hadookie** [comment]
This bug also exists on stock Pie in my Pixel 2.  Using an older version of the module had been working for me for some reason.

**Comment by P1N2O** [comment]
If you can confirm, I will revert the changes..

**Comment by hadookie** [comment]
I can confirm v2.02 has no issues on my Pixel 2, Pie, April update.  English.

**Comment by P1N2O** [comment]
@hadookie Done! Reverted..
